### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by ElectroBoi** [ElectroBoi/TugasBot#1]
1kb01 bot to do list

- [x] User Inputed link kuliah - Done
- [x] Updated Link Kuliah with GUI - Done
- [x] Latest User Update with TimeStamp - Done

- [x] Saving and Loading file to Json File - Done
- [ ] Activity Logging - Partially Done
    - [x]  User Input / Updated Link Kuliah Logging (With Before and after) - Done
    - [ ] User Input Tugas list - on going
    - [ ] Log File Creation
- [x] Console TimeStamp - Done

- [ ] User Inputed Tugas list with deadlines and matkul names - on going
- [ ] Per person Tugas Checklist

- [ ] Semester List
- [x] Mata kuliah register - Done

- [ ] User Count Caching - Partially Done
- [ ] Contribution Leaderboard (Last Priority)
